version: "3.8"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_bootcoin_db
    restart: always
    ports:
      - "27008:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  redis:
    image: redis:latest
    container_name: redis_bootcoin
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

volumes:
  mongo_data:
  redis_data: